### ISSUE TITLE
Reset pin?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [RioloGiuseppe/ssd1306-i2c-js#1]
Most docs about these devices mentioning tying the reset pin to a GPIO.

I don't see a mention of that here. Should I just tie reset to 3.3v?

**Comment by RioloGiuseppe** [comment]
Not all versions of this i2c bus display have RST pins. Mine, for example haven't this pin.

Reading the sources of other libraries, I saw that the pin is used to reset the display module at startup. 
If you have this pin you can connect to vcc or you can manage the reset gpio. In this case before call `init` function you should put low for a few milliseconds and then high, the gpio used for reset.

**Comment by GeoffreyPlitt** [comment]
Sounds good, thanks for the response!
